//! Cross-version binary format compatibility tests (roadmap #13).
//!
//! Verifies the current verifier against frozen binary fixtures checked into
//! git. Any change to the binary format that breaks deserialization of these
//! fixtures is a breaking change that requires a version bump and new fixtures.
//!
//! Fixtures are in tests/fixtures/ and generated by gen_fixtures.rs.
//!
//! # Compatibility matrix
//!
//! | Fixture                       | Expected result               |
//! |-------------------------------|-------------------------------|
//! | v4_audit_canonical.bin        | Deserializes + verifies pass  |
//! | v4_key_canonical.bin          | Deserializes, fields match    |
//! | reject_unknown_magic.bin      | Deserialization error (magic) |
//! | reject_truncated.bin          | Deserialization error          |
//! | reject_cross_format.bin       | Deserialization error          |
//! | reject_corrupted_bincode.bin  | Deserialization error          |

use verilm_core::constants::ModelConfig;
use verilm_core::serialize;
use verilm_core::types::{CommitmentVersion, RetainedLayerState, RetainedTokenState, ShellWeights};
use verilm_prover::{commit_minimal, open_v4, CapturedLayerScales, FullBindingParams};
use verilm_test_vectors::{forward_pass, generate_key, generate_model, LayerWeights};
use verilm_verify::{AuditCoverage, Verdict};

/// Thin wrapper: routes through the legacy verifier while canonical is validated.
fn verify_v4_compat(
    key: &verilm_core::types::VerifierKey,
    response: &verilm_core::types::V4AuditResponse,
    expected_prompt_token_ids: Option<&[u32]>,
) -> verilm_verify::V4VerifyReport {
    verilm_verify::verify_v4_legacy(key, response, expected_prompt_token_ids, None, None)
}

const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

fn fixture(name: &str) -> Vec<u8> {
    let path = format!("{}/{}", FIXTURES, name);
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture {} not found: {} — run gen_fixtures first", name, e))
}

struct ToyWeights<'a>(&'a [LayerWeights]);

impl ShellWeights for ToyWeights<'_> {
    fn weight(&self, layer: usize, mt: verilm_core::constants::MatrixType) -> &[i8] {
        let lw = &self.0[layer];
        match mt {
            verilm_core::constants::MatrixType::Wq => &lw.wq,
            verilm_core::constants::MatrixType::Wk => &lw.wk,
            verilm_core::constants::MatrixType::Wv => &lw.wv,
            verilm_core::constants::MatrixType::Wo => &lw.wo,
            verilm_core::constants::MatrixType::Wg => &lw.wg,
            verilm_core::constants::MatrixType::Wu => &lw.wu,
            verilm_core::constants::MatrixType::Wd => &lw.wd,
            verilm_core::constants::MatrixType::LmHead => panic!("no LmHead"),
        }
    }
}

fn retained_from_traces(traces: &[verilm_core::types::LayerTrace]) -> RetainedTokenState {
    RetainedTokenState {
        layers: traces
            .iter()
            .map(|lt| RetainedLayerState {
                a: lt.a.clone(),
                scale_a: lt.scale_a.unwrap_or(1.0),
            })
            .collect(),
    }
}

fn unit_scales(n_layers: usize) -> Vec<CapturedLayerScales> {
    vec![CapturedLayerScales { scale_x_attn: 1.0, scale_x_ffn: 1.0, scale_h: 1.0 }; n_layers]
}

// ===========================================================================
// Canonical pass fixtures
// ===========================================================================

#[test]
fn frozen_v4_audit_deserializes() {
    let data = fixture("v4_audit_canonical.bin");
    assert_eq!(&data[..4], b"VV4A", "fixture magic should be VV4A");

    let response = serialize::deserialize_v4_audit(&data)
        .expect("canonical audit fixture must deserialize");

    assert_eq!(response.token_index, 0);
    assert_eq!(response.token_id, 42);
    assert_eq!(response.commitment.version, CommitmentVersion::V4);
    assert_eq!(response.commitment.n_tokens, 1);
    assert!(response.shell_opening.is_some());
    assert!(response.commitment.seed_commitment.is_some());
    assert!(response.commitment.prompt_hash.is_some());
}

#[test]
fn frozen_v4_audit_verifies_pass() {
    let data = fixture("v4_audit_canonical.bin");
    let response = serialize::deserialize_v4_audit(&data).unwrap();

    // Reconstruct the same key deterministically.
    let cfg = ModelConfig::toy();
    let model = generate_model(&cfg, 12345);
    let key = generate_key(&cfg, &model, [1u8; 32]);

    let report = verify_v4_compat(&key, &response, None);
    assert_eq!(report.verdict, Verdict::Pass,
        "frozen fixture must verify pass, failures: {:?}", report.failures);
    assert!(report.checks_run >= 15,
        "expected >= 15 checks, got {}", report.checks_run);
    match &report.coverage {
        AuditCoverage::Full { layers_checked } => {
            assert_eq!(*layers_checked, cfg.n_layers);
        }
        other => panic!("expected Full coverage, got {:?}", other),
    }
}

#[test]
fn frozen_v4_audit_byte_stable() {
    // Re-generate the same response and verify byte-identical serialization.
    let cfg = ModelConfig::toy();
    let model = generate_model(&cfg, 12345);
    let input: Vec<i8> = (0..cfg.hidden_dim as i8).collect();
    let traces = forward_pass(&cfg, &model, &input);
    let retained = retained_from_traces(&traces);

    let params = FullBindingParams {
        token_ids: &[42],
        prompt: b"frozen fixture prompt",
        sampling_seed: [7u8; 32],
        manifest: None,
        n_prompt_tokens: Some(1),
    };
    let (_commitment, state) = commit_minimal(vec![retained], &params, None, vec![unit_scales(cfg.n_layers)], None);
    let response = open_v4(
        &state, 0, &ToyWeights(&model), &cfg, &[], None, None, None, None, false,
    );
    let fresh_binary = serialize::serialize_v4_audit(&response);
    let frozen = fixture("v4_audit_canonical.bin");

    assert_eq!(
        fresh_binary, frozen,
        "serialized audit binary is not byte-stable — format drift detected \
         (fresh {} bytes vs frozen {} bytes)",
        fresh_binary.len(), frozen.len()
    );
}

#[test]
fn frozen_v4_key_deserializes() {
    let data = fixture("v4_key_canonical.bin");
    assert_eq!(&data[..4], b"VKEY", "fixture magic should be VKEY");

    let key = serialize::deserialize_key(&data)
        .expect("canonical key fixture must deserialize");

    let cfg = ModelConfig::toy();
    assert_eq!(key.config.n_layers, cfg.n_layers);
    assert_eq!(key.config.hidden_dim, cfg.hidden_dim);
    assert_eq!(key.config.vocab_size, cfg.vocab_size);
    assert_eq!(key.seed, [1u8; 32]);
}

#[test]
fn frozen_v4_key_byte_stable() {
    let cfg = ModelConfig::toy();
    let model = generate_model(&cfg, 12345);
    let key = generate_key(&cfg, &model, [1u8; 32]);
    let fresh_binary = serialize::serialize_key(&key);
    let frozen = fixture("v4_key_canonical.bin");

    assert_eq!(
        fresh_binary, frozen,
        "serialized key binary is not byte-stable — format drift detected \
         (fresh {} bytes vs frozen {} bytes)",
        fresh_binary.len(), frozen.len()
    );
}

#[test]
fn frozen_v4_key_used_with_frozen_audit() {
    // The frozen key must be usable with the frozen audit response.
    let key_data = fixture("v4_key_canonical.bin");
    let audit_data = fixture("v4_audit_canonical.bin");

    let key = serialize::deserialize_key(&key_data).unwrap();
    let response = serialize::deserialize_v4_audit(&audit_data).unwrap();

    let report = verify_v4_compat(&key, &response, None);
    assert_eq!(report.verdict, Verdict::Pass,
        "frozen key + frozen audit must verify pass, failures: {:?}", report.failures);
}

// ===========================================================================
// Rejection fixtures
// ===========================================================================

#[test]
fn frozen_reject_unknown_magic() {
    let data = fixture("reject_unknown_magic.bin");
    assert_eq!(&data[..4], b"VV5A", "fixture should have VV5A magic");

    let result = serialize::deserialize_v4_audit(&data);
    assert!(result.is_err(), "unknown magic must be rejected");
    let err = result.unwrap_err();
    assert!(err.contains("magic"), "error should mention magic: {}", err);
}

#[test]
fn frozen_reject_truncated() {
    let data = fixture("reject_truncated.bin");
    assert!(data.len() < 20, "truncated fixture should be small");

    let result = serialize::deserialize_v4_audit(&data);
    assert!(result.is_err(), "truncated payload must be rejected");
}

#[test]
fn frozen_reject_cross_format() {
    let data = fixture("reject_cross_format.bin");
    assert_eq!(&data[..4], b"VV4A", "cross-format fixture has audit magic");

    let result = serialize::deserialize_v4_audit(&data);
    assert!(result.is_err(),
        "key body with audit magic must be rejected (cross-format)");
}

#[test]
fn frozen_reject_corrupted_bincode() {
    let data = fixture("reject_corrupted_bincode.bin");
    assert_eq!(&data[..4], b"VV4A", "corrupted fixture has correct magic");

    let result = serialize::deserialize_v4_audit(&data);
    assert!(result.is_err(),
        "valid zstd + garbage bincode must be rejected");
    let err = result.unwrap_err();
    assert!(err.contains("deserialization"), "error should mention deserialization: {}", err);
}

// ===========================================================================
// Version field preservation
// ===========================================================================

#[test]
fn frozen_commitment_version_is_v4() {
    let data = fixture("v4_audit_canonical.bin");
    let response = serialize::deserialize_v4_audit(&data).unwrap();
    assert_eq!(response.commitment.version, CommitmentVersion::V4);
}

#[test]
fn frozen_key_version_preserved() {
    let data = fixture("v4_key_canonical.bin");
    let key = serialize::deserialize_key(&data).unwrap();
    assert_eq!(key.version, 1, "key version should be 1");
}

// ===========================================================================
// Forward-compatibility: unknown versions fail-closed
// ===========================================================================

#[test]
fn future_magic_vv5a_rejected() {
    // Synthesize a future "VV5A" payload (same body as canonical).
    let mut data = fixture("v4_audit_canonical.bin");
    data[2] = b'5';
    assert!(serialize::deserialize_v4_audit(&data).is_err());
}

#[test]
fn future_magic_vv9z_rejected() {
    let mut data = fixture("v4_audit_canonical.bin");
    data[2] = b'9';
    data[3] = b'Z';
    assert!(serialize::deserialize_v4_audit(&data).is_err());
}

// ===========================================================================
// Canonical full-bridge fixtures (pass canonical::verify_response)
// ===========================================================================

#[test]
fn frozen_fullbridge_audit_passes_canonical_verification() {
    let key_data = fixture("v4_key_fullbridge.bin");
    let audit_data = fixture("v4_audit_fullbridge.bin");

    let key = serialize::deserialize_key(&key_data).unwrap();
    let response = serialize::deserialize_v4_audit(&audit_data).unwrap();

    let report = verilm_verify::canonical::verify_response(&key, &response, None, None);
    assert_eq!(
        report.verdict,
        Verdict::Pass,
        "frozen fullbridge fixture must pass canonical verification, failures: {:?}",
        report.failures
    );
    assert!(
        report.checks_run >= 20,
        "expected >= 20 canonical checks, got {}",
        report.checks_run
    );
    match &report.coverage {
        AuditCoverage::Full { layers_checked } => {
            assert!(*layers_checked >= 2, "expected >= 2 layers checked");
        }
        other => panic!("expected Full coverage, got {:?}", other),
    }
}

#[test]
fn frozen_fullbridge_has_manifest_and_bridge() {
    let audit_data = fixture("v4_audit_fullbridge.bin");
    let response = serialize::deserialize_v4_audit(&audit_data).unwrap();

    assert!(response.manifest.is_some(), "canonical fixture must have manifest");
    let shell = response.shell_opening.as_ref().expect("must have shell");
    assert!(shell.initial_residual.is_some(), "canonical fixture must have initial_residual");
    assert!(shell.embedding_proof.is_some(), "canonical fixture must have embedding_proof");
    assert!(response.commitment.manifest_hash.is_some(), "commitment must have manifest_hash");
    assert!(response.commitment.input_spec_hash.is_some(), "commitment must have input_spec_hash");
    assert!(response.commitment.model_spec_hash.is_some(), "commitment must have model_spec_hash");
}

#[test]
fn future_key_magic_vke2_rejected() {
    let mut data = fixture("v4_key_canonical.bin");
    data[3] = b'2'; // VKEY → VKE2
    assert!(serialize::deserialize_key(&data).is_err());
}

// ===========================================================================
// Cross-format misuse
// ===========================================================================

#[test]
fn frozen_key_as_audit_rejected() {
    let data = fixture("v4_key_canonical.bin");
    assert!(serialize::deserialize_v4_audit(&data).is_err(),
        "key fixture must not parse as audit response");
}

#[test]
fn frozen_audit_as_key_rejected() {
    let data = fixture("v4_audit_canonical.bin");
    assert!(serialize::deserialize_key(&data).is_err(),
        "audit fixture must not parse as verifier key");
}

// ===========================================================================
// Fixture integrity (SHA-256 checksums)
// ===========================================================================

#[test]
fn frozen_audit_sha256_pinned() {
    use sha2::{Sha256, Digest};
    let data = fixture("v4_audit_canonical.bin");
    let hash = hex::encode(Sha256::digest(&data));
    // Pinned on first generation. Update ONLY on intentional format change.
    assert_eq!(
        hash,
        "3891dd7b022330dbb0b4f7a83eff79ab1ba7d38bca9bc8ed6d9b5e66493ac09c",
        "audit fixture checksum drifted — was the fixture silently regenerated?"
    );
}

#[test]
fn frozen_key_sha256_pinned() {
    use sha2::{Sha256, Digest};
    let data = fixture("v4_key_canonical.bin");
    let hash = hex::encode(Sha256::digest(&data));
    // Pinned on first generation. Update ONLY on intentional format change.
    assert_eq!(
        hash,
        "d8fa0f945799cf180260d672f7d8b3f00f4b7cb3fea1871005e935f4b988ab9e",
        "key fixture checksum drifted — was the fixture silently regenerated?"
    );
}
